### ISSUE TITLE
Message: unknown error: failed to change window state to 'minimized', current state is 'normal'

### ISSUE THREAD

**Issue by riccardolunardi** [rawandahmad698/pyCFSolver#1]
Hello,
just wanted to bring you attention on this error.
I tried it on 2 different machine and the traceback it's the same. Perhaps is it something related to the last update or am I missing something?
Thanks!

**Traceback**
```
2023-07-29 15:11:30 INFO     FlareSolverr 0.1
2023-07-29 15:11:30 INFO     Testing web browser installation...
2023-07-29 15:11:30 INFO     Platform: Linux-5.4.0-125-generic-x86_64-with-glibc2.31
2023-07-29 15:11:30 INFO     Chrome / Chromium path: /snap/bin/chromium
2023-07-29 15:11:30 INFO     Chrome / Chromium major version: 115
2023-07-29 15:11:30 INFO     Launching web browser...
2023-07-29 15:11:35 ERROR    Message: unknown error: failed to change window state to 'minimized', current state is 'normal'
  (Session info: chrome=115.0.5790.102)
Stacktrace:
#0 0x555cb21d74e3 <unknown>
#1 0x555cb1f06c76 <unknown>
#2 0x555cb1ee433f <unknown>
#3 0x555cb1ee2ff5 <unknown>
#4 0x555cb1ee3788 <unknown>
#5 0x555cb1f8cfa6 <unknown>
#6 0x555cb1f62012 <unknown>
#7 0x555cb1f7a30e <unknown>
#8 0x555cb1f61de3 <unknown>
#9 0x555cb1f372dd <unknown>
#10 0x555cb1f3834e <unknown>
#11 0x555cb21973e4 <unknown>
#12 0x555cb219b3d7 <unknown>
#13 0x555cb21a5b20 <unknown>
#14 0x555cb219c023 <unknown>
#15 0x555cb216a1aa <unknown>
#16 0x555cb21c06b8 <unknown>
#17 0x555cb21c0847 <unknown>
#18 0x555cb21d0243 <unknown>
#19 0x7fa19d6f3609 start_thread
Traceback (most recent call last):
  File "/root/pyCFSolver/src/utils.py", line 104, in get_webdriver
    driver.minimize_window()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 619, in minimize_window
    self.execute(Command.MINIMIZE_WINDOW)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: failed to change window state to 'minimized', current state is 'normal'
  (Session info: chrome=115.0.5790.102)
Stacktrace:
#0 0x555cb21d74e3 <unknown>
#1 0x555cb1f06c76 <unknown>
#2 0x555cb1ee433f <unknown>
#3 0x555cb1ee2ff5 <unknown>
#4 0x555cb1ee3788 <unknown>
#5 0x555cb1f8cfa6 <unknown>
#6 0x555cb1f62012 <unknown>
#7 0x555cb1f7a30e <unknown>
#8 0x555cb1f61de3 <unknown>
#9 0x555cb1f372dd <unknown>
#10 0x555cb1f3834e <unknown>
#11 0x555cb21973e4 <unknown>
#12 0x555cb219b3d7 <unknown>
#13 0x555cb21a5b20 <unknown>
#14 0x555cb219c023 <unknown>
#15 0x555cb216a1aa <unknown>
#16 0x555cb21c06b8 <unknown>
#17 0x555cb21c0847 <unknown>
#18 0x555cb21d0243 <unknown>
#19 0x7fa19d6f3609 start_thread

Traceback (most recent call last):
  File "/root/pyCFSolver/src/utils.py", line 104, in get_webdriver
    driver.minimize_window()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 619, in minimize_window
    self.execute(Command.MINIMIZE_WINDOW)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: failed to change window state to 'minimized', current state is 'normal'
  (Session info: chrome=115.0.5790.102)
Stacktrace:
#0 0x555cb21d74e3 <unknown>
#1 0x555cb1f06c76 <unknown>
#2 0x555cb1ee433f <unknown>
#3 0x555cb1ee2ff5 <unknown>
#4 0x555cb1ee3788 <unknown>
#5 0x555cb1f8cfa6 <unknown>
#6 0x555cb1f62012 <unknown>
#7 0x555cb1f7a30e <unknown>
#8 0x555cb1f61de3 <unknown>
#9 0x555cb1f372dd <unknown>
#10 0x555cb1f3834e <unknown>
#11 0x555cb21973e4 <unknown>
#12 0x555cb219b3d7 <unknown>
#13 0x555cb21a5b20 <unknown>
#14 0x555cb219c023 <unknown>
#15 0x555cb216a1aa <unknown>
#16 0x555cb21c06b8 <unknown>
#17 0x555cb21c0847 <unknown>
#18 0x555cb21d0243 <unknown>
#19 0x7fa19d6f3609 start_thread


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/pyCFSolver/src/utils.py", line 198, in get_user_agent
    driver = get_webdriver(req=req)
  File "/root/pyCFSolver/src/utils.py", line 124, in get_webdriver
    raise Exception(f'Error launching web browser: {e} (line {lineno})')
Exception: Error launching web browser: Message: unknown error: failed to change window state to 'minimized', current state is 'normal'
  (Session info: chrome=115.0.5790.102)
Stacktrace:
#0 0x555cb21d74e3 <unknown>
#1 0x555cb1f06c76 <unknown>
#2 0x555cb1ee433f <unknown>
#3 0x555cb1ee2ff5 <unknown>
#4 0x555cb1ee3788 <unknown>
#5 0x555cb1f8cfa6 <unknown>
#6 0x555cb1f62012 <unknown>
#7 0x555cb1f7a30e <unknown>
#8 0x555cb1f61de3 <unknown>
#9 0x555cb1f372dd <unknown>
#10 0x555cb1f3834e <unknown>
#11 0x555cb21973e4 <unknown>
#12 0x555cb219b3d7 <unknown>
#13 0x555cb21a5b20 <unknown>
#14 0x555cb219c023 <unknown>
#15 0x555cb216a1aa <unknown>
#16 0x555cb21c06b8 <unknown>
#17 0x555cb21c0847 <unknown>
#18 0x555cb21d0243 <unknown>
#19 0x7fa19d6f3609 start_thread
 (line 104)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/pyCFSolver/src/flaresolverr.py", line 95, in <module>
    flaresolverr_service.test_browser_installation()
  File "/root/pyCFSolver/src/flaresolverr_service.py", line 77, in test_browser_installation
    user_agent = utils.get_user_agent()
  File "/root/pyCFSolver/src/utils.py", line 203, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Error launching web browser: Message: unknown error: failed to change window state to 'minimized', current state is 'normal'
  (Session info: chrome=115.0.5790.102)
Stacktrace:
#0 0x555cb21d74e3 <unknown>
#1 0x555cb1f06c76 <unknown>
#2 0x555cb1ee433f <unknown>
#3 0x555cb1ee2ff5 <unknown>
#4 0x555cb1ee3788 <unknown>
#5 0x555cb1f8cfa6 <unknown>
#6 0x555cb1f62012 <unknown>
#7 0x555cb1f7a30e <unknown>
#8 0x555cb1f61de3 <unknown>
#9 0x555cb1f372dd <unknown>
#10 0x555cb1f3834e <unknown>
#11 0x555cb21973e4 <unknown>
#12 0x555cb219b3d7 <unknown>
#13 0x555cb21a5b20 <unknown>
#14 0x555cb219c023 <unknown>
#15 0x555cb216a1aa <unknown>
#16 0x555cb21c06b8 <unknown>
#17 0x555cb21c0847 <unknown>
#18 0x555cb21d0243 <unknown>
#19 0x7fa19d6f3609 start_thread
 (line 104)
```

**Comment by rawandahmad698** [comment]
Hi. how did i miss this, i didn't get a notification, are you still encountering this issue?
